# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'
install:
  ps: Bootstrap

# Adapt as necessary starting from here

on_failure:
  - 7z a logs.zip *.Rcheck
  - appveyor PushArtifact logs.zip

build_script:
  - set JAVA_HOME=C:\Program Files (x86)\Java\jdk1.8.0\jre
  - set PATH=C:\Program Files (x86)\Java\jdk1.8.0\bin;C:\Program Files (x86)\Java\jdk1.8.0\jre\bin\server;%PATH%
  - ls "C:\Program Files (x86)\Java\jdk1.8.0\jre"
  - travis-tool.sh install_deps

test_script:
  - travis-tool.sh run_tests

after_test:
  - 7z a logs.zip *.Rcheck


artifacts:
  - path: 'logs.zip'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Linux Package

  - path: '\*_*.zip'
    name: Windows Package
